// Generated by https://quicktype.io

export interface FulfillmentRating {
  dst: string
  dstpk: Dstpk
  rating: FulfillmentRatingInformation
  sig: Sig[]
  src: string
  srcpk: Dstpk
  type: string
}

export interface Dstpk {
  bitcoin: string
  identity: string
}

export interface FulfillmentRatingInformation {
  key: string
  average: number
  buyerRating: BuyerRating
  note: string
  orderId: string
  ratingSignature: RatingSignature
  slug: string
  timestamp: string
}

export interface BuyerRating {
  comment: string
  fields: Field[]
}

export interface Field {
  max: number
  score: number
  type: string
  weight: number
}

export interface RatingSignature {
  metadata: Metadata
  signature: string
}

export interface Metadata {
  listingSlug: string
  listingTitle: string
  ratingKey: string
  thumbnail: Thumbnail
}

export interface Thumbnail {
  filename: string
  large: string
  medium: string
  original: string
  small: string
  tiny: string
}

export interface Sig {
  section: string
  signatureBytes: string
}
